#!/usr/bin/env bash
rpm -i https://s3-eu-west-1.amazonaws.com/widdix-aws-ec2-ssh-releases-eu-west-1/aws-ec2-ssh-1.4.0-1.el7.centos.noarch.rpm

sleep 5

cat > /etc/aws-ec2-ssh.conf << EOL
IAM_AUTHORIZED_GROUPS="ssh_key_man_admin_test"
LOCAL_MARKER_GROUP="iam-synced-users"
LOCAL_GROUPS=""
SUDOERS_GROUPS=" ssh_key_man_admin_test"
ASSUMEROLE=""
#Remove or set to 0 if you are done with configuration
# /etc/cron.d/aws-ec2-ssh
DONOTSYNC=0 
EOL

source /usr/bin/import_users.sh

